name: Build application

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HANGOUT_SAFARI_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - run: echo "${{ github.event_name }}"

      - run: echo "Installing dependencies ⏬"
        # Add your installation commands here

      - run: npm ci
        # Add any other necessary setup steps

      - run: echo $PATH

      - run: echo "Building application 👷"
      - run: npm run build --if-present

      - run: echo "Building is complete ✅"

      - run: echo "Starting tests 🧪"
      - run: npm run test

      - run: echo "Tests have passed ✅"

      - run: echo "Running formating"
      - run: npm run format

      - name: Get latest commit message
        id: get_commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Push changes
        if: success() && !contains(steps.get_commit_message.outputs.message, 'BuildWorkflow')
        run: |
          set -e  
          git config user.name "wpsimon09"
          git config user.email "wpsimon09@users.noreply.github.com"
          git add .

          # Use 'git diff-index' to check if there are changes to commit
          if ! git diff-index --quiet HEAD --; then
          git commit -m "BuildWorkflow: Linted and built code"
          git push
          else
          echo "No changes to commit."
          fi
