name: Build application
run-name: ${{ github.actor }} is building the application 🏗️
on: 
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  
      - run: echo "Instaling dependencies ⏬"
      - run: npm ci   
      - run: echo "Building applicatin 👷"
      - run: npm run build --if-present
      - run: echo "Building is complete ✅"
      - run: 
    